version: '3.8'

services:
  fshare-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: get-folder-linksvip-net
    ports:
      - "8080:8080"
    restart: unless-stopped
